import type { Metadata } from "next";
import localFont from "next/font/local";
import { Suspense } from "react";
import "./globals.css";

const pretendard = localFont({
    src: [
        {
            path: "../../public/fonts/PretendardLight.woff2",
            weight: "300",
            style: "normal",
        },
        {
            path: "../../public/fonts/PretendardRegular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/PretendardMedium.woff2",
            weight: "500",
            style: "normal",
        },
        {
            path: "../../public/fonts/PretendardSemiBold.woff2",
            weight: "600",
            style: "normal",
        },
        {
            path: "../../public/fonts/PretendardBold.woff2",
            weight: "700",
            style: "normal",
        },
    ],
    variable: "--font-pretendard",
});

export const metadata: Metadata = {
    title: "미소티켓",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.png",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Suspense>
            <html lang="ko" className={pretendard.className}>
                <body>{children}</body>
            </html>
        </Suspense>
    );
}
